var CreateComponent = function () {
    this.createButton = element(by.buttonText('CREATE'));
    this.editButton = element(by.buttonText('EDIT'));
    this.cancelButton = element(by.buttonText('Cancel'));
    this.profileIcon = element(by.id('accountCircle'));
    this.logoutButton = element(by.buttonText('Logout'));
    this.descriptionTaskField = element(by.id('newTaskDescription'));
    this.okButton = element(by.buttonText('OK'));
    this.itemName = 'block';
    this.password = 'Fluance2025*';
    this.employmentDegree = 1;
    this.taskOptions = element(by.id('taskOptions'));
    this.itemToBeCreated = element(by.id('itemToBeCreated'));
    this.projectNameField = element(by.id('newProjectName'));
    this.projectOptions = element(by.id('projectOptions'));
    this.clientNameField = element(by.id('newClientName'));
    this.clientOptions = element(by.id('clientOptions'));
    this.usernameField = element(by.id('username'));
    this.passwordField = element(by.id('password'));
    this.confirmPasswordField = element(by.id('confirmPassword'));
    this.employmentDegreeField = element(by.id('employmentDegree'));
    this.deleteUserButton = element(by.buttonText('Delete user'));
}
module.exports = CreateComponent;